### ISSUE TITLE
joinPolys intersection fails when polygons don't intersect

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pbs-software/pbs-mapping#27]
```
A user just sent this report:

***********

I have a problem with the function joinPolys when the two polygons compared do 
not intersect (with operation="INT"). I have no problem when I compare polygons 
that actually do intersect. The following command reports an error:

if (nrow(results) > 0) {

I didn't have this issue with an older version of the package (but I do not 
know which one).

***********

JTS: Very likely this has resulted from our conversion to "clipper".

```

Original issue reported on code.google.com by `schnu...@shaw.ca` on 18 Jul 2013 at 11:29

**Comment by haighr** [comment]
The intersection logically returns NULL and the test need only be for NULL; however, you could double check for NULL and nrow(results)==0, just in case:

polyA <- as.PolySet(data.frame(
	PID=rep(1,4), POS=1:4, X=c(0,2,2,0), Y=c(0,0,2,2)), projection=1)
N <- 4
X = cos(seq(0, 2*pi, length = N))
Y = sin(seq(0, 2*pi, length = N))
polyB = as.PolySet(data.frame(
	PID=rep(1,N), POS=1:N, X=5*X+5, Y=5*Y), projection=1)
plotPolys(NULL, xlim=c(0,10), ylim=c(-5,5), projection=1)
addPolys(polyA, col="blue")
addPolys(polyB, col="red")
polyAB = joinPolys(polyA, polyB, op="INT")
print(polyAB)
if (is.null(polyAB)||nrow(polyAB)==0)
	cat("Polys do not intersect\n")
Output:
NULL
Polys do not intersect
